### ISSUE TITLE
12th question

### ISSUE THREAD

**Issue by alvinbengeorge** [agnirudrasil/12-practical#10]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/alvinbengeorge/OneDrive/Desktop/others/F/Python/Python_Git/12-practical/src/question_12/main.py", line 29, in <module>
    if data["empNo"] == "123":
TypeError: list indices must be integers or slices, not str
```

Got this for 12th

**Comment by agnirudrasil** [comment]
#12 by @PythonicNoob fixed it
